FROM nvidia/cuda:11.4.0-cudnn8-devel-centos7

ENV PATH /usr/local/python3/bin/:$PATH
RUN set -ex \
    && yum update -y \
    && yum install -y deltarpm tar vim libffi-devel zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make initscripts wget \
    && yum clean all \
    && wget https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz \
    && tar -zxvf Python-3.8.0.tgz \
    && cd Python-3.8.0 \
    && ./configure prefix=/usr/local/python3 \
    && make \
    && make install \
    && make clean \
    && rm -rf /Python-3.8.0* \
    && yum install -y epel-release \
    && mv /usr/bin/python /usr/bin/python27 \
    && ln -s /usr/local/python3/bin/python3.8 /usr/bin/python \
    && ln -s /usr/local/python3/bin/pip3 /usr/bin/pip \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/libexec/urlgrabber-ext-down \
    && sed -i "s#/usr/bin/python#/usr/bin/python2.7#" /usr/bin/yum

RUN set -ex \
    && python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --upgrade pip \
    && python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple opencv-python \
    && python -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple opencv-python-headless

# COPY java-app.tar.gz /tmp
# COPY data.tar.gz /tmp

RUN set -ex \
    && mkdir -p /workspace \
    # && tar zxf /tmp/java-app.tar.gz -C /workspace \
    # && tar zxf /tmp/data.tar.gz -C /workspace \
    && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*


WORKDIR /workspace/docker-ceping1

ENTRYPOINT [ "/usr/sbin/init" ]

# docker build -f Dockerfile-centos -t msbrm/fat_gpu:2023centos7 .